<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Ludeka.Application\Ludeka.Application.csproj" />
    <ProjectReference Include="..\Ludeka.Infrastructure\Ludeka.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>ludeka-web-user-secrets-2026</UserSecretsId>
  </PropertyGroup>

</Project>
